# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c62004b424d2407e41dc75814af6f27f1bc15db32e0c0debd81e2d8919700bd5dc11ddd73024cdfc0ae9b347d02019909efedf922325f419b899ee02f8c44967

test:
  secret_key_base: 4bbfa67cf52ae8b3bfe9397a3b790cb62c647fe4bc6ebf72f00528fd37da8f561776a18c61ac80986b1c2bb4e809273fa88442b74e98e711a3375579ae8b32be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
